import Link from "next/link";
import type { CharacterValidationSummary as Summary } from "@/character/character-validation-summary";

const statusStyles: Record<Summary["presentation"], string> = { Validated: "border-success/40 bg-success/5", "Needs Review": "border-warning/50 bg-warning/5", "Rules Issue Found": "border-danger/50 bg-danger/5" };

export function CharacterValidationSummary({ summary, readOnly = false, compact = false, className = "mt-6" }: { summary: Summary; readOnly?: boolean; compact?: boolean; className?: string }) {
  return <section aria-label="Character validation" className={className}>
    <details className={`group rounded-2xl border ${statusStyles[summary.presentation]}`}>
      <summary className={`flex cursor-pointer list-none flex-wrap items-center justify-between gap-3 rounded-2xl marker:content-none focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand ${compact ? "p-3" : "p-5"}`}>
        <span>{compact ? null : <span className="block text-xs font-semibold tracking-[0.16em] text-text-muted uppercase">Validation summary</span>}<span className={`${compact ? "text-base" : "mt-1 text-lg"} block font-semibold`}>{summary.presentation}</span></span>
        <span className="flex items-center gap-3"><span className="text-sm text-text-muted"><span className="font-semibold text-text-primary">{summary.validatedCount}</span> validated · <span className="font-semibold text-text-primary">{summary.unvalidatedCount}</span> need review · <span className="font-semibold text-text-primary">{summary.invalidCount}</span> rules issues</span><svg aria-hidden="true" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="2" className="size-5 shrink-0 text-text-muted transition-transform group-open:rotate-180"><path d="m5 7.5 5 5 5-5" /></svg></span>
      </summary>
      <div className={`border-t border-border ${compact ? "px-3 pt-3 pb-3" : "px-5 pt-4 pb-5"}`}>
        {summary.presentation === "Validated" ? <p className="text-sm text-text-muted">Nexus confirmed every recorded class, ancestry, background, and inventory selection.</p> : <><p className="text-sm text-text-muted">This is advisory only. {readOnly ? "Player notes and validation details are read-only." : "You can keep editing and using this character while these selections are reviewed."}</p><ul className={compact ? "mt-3 space-y-2" : "mt-4 space-y-3"}>{summary.details.map((detail) => <li key={detail.key} className={`rounded-xl border border-border bg-surface ${compact ? "p-3" : "p-4"}`}><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="text-xs font-semibold tracking-wide text-text-muted uppercase">{detail.category}</p><p className="mt-1 font-semibold">{detail.selection}</p></div>{readOnly ? null : <Link className="text-sm font-semibold text-brand hover:underline" href={detail.editHref}>Review option</Link>}</div><dl className={`${compact ? "mt-2 gap-1" : "mt-3 gap-2"} grid text-sm`}><div><dt className="inline font-semibold">Status: </dt><dd className="inline text-text-muted">{detail.status === "invalid" ? "Invalid" : "Unvalidated"}</dd></div><div><dt className="inline font-semibold">Source: </dt><dd className="inline text-text-muted">{detail.sourceHref ? <a className="font-semibold text-brand hover:underline" href={detail.sourceHref} target="_blank" rel="noreferrer">{detail.source ?? "Open source"}</a> : detail.source ?? "Not recorded"}</dd></div><div><dt className="inline font-semibold">Reason: </dt><dd className="inline text-text-muted">{detail.issues.map(({ message }) => message).join(" ")}</dd></div><div><dt className="inline font-semibold">Player note: </dt><dd className="inline whitespace-pre-wrap text-text-muted">{detail.playerNote ?? "No note added."}</dd></div></dl></li>)}</ul></>}
      </div>
    </details>
  </section>;
}
