"use client";
import { useState, useTransition } from "react";
import { Dialog } from "@/app/dialog";
import { OptionCatalogSearch, type SelectedCatalogOption } from "@/app/characters/option-catalog-search";
import { createOptionCardAction, type OptionCardState } from "./actions";

const inputClass = "mt-1 w-full rounded-xl border border-border-strong bg-surface px-3 py-2 outline-none focus:border-brand";
const emptyCatalog = { id: "", name: "", identity: "", title: "", url: "" };

export function AddCharacterOptionDialog({ characterId, currentLevel }: { characterId: string; currentLevel: number }) {
  const [open, setOpen] = useState(false); const [kind, setKind] = useState<"feat" | "heritage">("feat"); const [category, setCategory] = useState<"class" | "ancestry" | "skill" | "general" | "">("");
  const [method, setMethod] = useState<"selected" | "awarded">("selected"); const [catalog, setCatalog] = useState(emptyCatalog); const [state, setState] = useState<OptionCardState>({}); const [saving, startSaving] = useTransition();
  const choose = (option: SelectedCatalogOption) => setCatalog({ id: option.id, name: option.name, identity: option.sourceMaterialIdentity ?? "", title: option.sourceMaterialTitle ?? "", url: option.sourceUrl ?? "" });
  const reset = () => { setKind("feat"); setCategory(""); setMethod("selected"); setCatalog(emptyCatalog); setState({}); };
  return <><button type="button" onClick={() => { reset(); setOpen(true); }} className="rounded-full border border-border-strong px-4 py-2 text-sm font-semibold text-brand">Add feat or heritage</button>{open ? <Dialog open title="Add feat or heritage" description="Record a selection and optionally link it to the Archives of Nethys catalog." onClose={() => setOpen(false)} closeLabel="Close add feat or heritage" className="max-w-2xl"><form action={(formData) => startSaving(async () => { const result = await createOptionCardAction(characterId, formData); setState(result); if (result.saved) setOpen(false); })} className="mt-5 space-y-4">
    <div className="grid gap-3 sm:grid-cols-2"><div><label htmlFor="new-option-kind" className="text-sm font-semibold">Option type</label><select id="new-option-kind" name="selectionKind" value={kind} onChange={(event) => { setKind(event.currentTarget.value as "feat" | "heritage"); setCatalog(emptyCatalog); }} className={inputClass}><option value="feat">Feat</option><option value="heritage">Heritage</option></select></div><div><label htmlFor="new-option-name" className="text-sm font-semibold">Name</label><input id="new-option-name" name="name" required maxLength={200} value={catalog.name} onChange={(event) => setCatalog((value) => ({ ...value, id: "", name: event.currentTarget.value }))} className={inputClass}/></div></div>
    <input type="hidden" name="characterOptionId" value={catalog.id}/><input type="hidden" name="sourceMaterialIdentity" value={catalog.identity}/><input type="hidden" name="sourceMaterialTitle" value={catalog.title}/><input type="hidden" name="sourceUrl" value={catalog.url}/>
    <OptionCatalogSearch key={`${kind}-${catalog.name}`} kind={kind} category={category || null} initialQuery={catalog.name} onSelected={choose}/>
    <div className="grid gap-3 sm:grid-cols-2"><div><label htmlFor="new-option-level" className="text-sm font-semibold">Acquired level</label><input id="new-option-level" name="acquiredLevel" type="number" min={1} max={20} required defaultValue={currentLevel} className={inputClass}/></div>{kind === "feat" ? <div><label htmlFor="new-option-category" className="text-sm font-semibold">Rules category</label><select id="new-option-category" name="featCategory" value={category} onChange={(event) => setCategory(event.currentTarget.value as typeof category)} className={inputClass}><option value="">Unknown</option>{["class", "ancestry", "skill", "general"].map((value) => <option key={value} value={value}>{value}</option>)}</select></div> : null}</div>
    <fieldset><legend className="text-sm font-semibold">Acquisition</legend><div className="mt-2 flex gap-5">{(["selected", "awarded"] as const).map((value) => <label key={value} className="flex items-center gap-2 capitalize"><input type="radio" name="acquisitionMethod" value={value} checked={method === value} onChange={() => setMethod(value)}/>{value}</label>)}</div></fieldset>
    {method === "awarded" ? <div><label htmlFor="new-option-origin" className="text-sm font-semibold">Grant origin <span className="font-normal text-text-muted">(optional)</span></label><input id="new-option-origin" name="grantOrigin" maxLength={300} className={inputClass}/></div> : null}
    <div><label htmlFor="new-option-note" className="text-sm font-semibold">Validation note <span className="font-normal text-text-muted">(optional)</span></label><textarea id="new-option-note" name="validationNote" rows={2} maxLength={1000} className={`${inputClass} resize-y`}/></div>
    {state.error ? <p role="alert" className="text-sm text-danger">{state.error}</p> : null}<div className="flex justify-end gap-3 border-t border-border pt-4"><button type="button" onClick={() => setOpen(false)} className="rounded-full border border-border-strong px-4 py-2 font-semibold">Cancel</button><button disabled={saving} className="rounded-full bg-brand px-5 py-2 font-semibold text-on-brand disabled:opacity-60">{saving ? "Adding…" : `Add ${kind}`}</button></div>
  </form></Dialog> : null}</>;
}
