"use client";

import { useState, useTransition } from "react";
import { Dialog } from "@/app/dialog";
import { importCharacterOptionAction } from "@/app/characters/character-options-actions";
import { OptionCatalogSearch } from "@/app/characters/option-catalog-search";
import type { CharacterOptionSelection } from "@/character/option-selections";
import { deleteOptionCardAction, updateOptionCardAction, type OptionCardState } from "./actions";

const inputClass = "mt-2 w-full rounded-xl border border-border-strong bg-surface px-4 py-3 outline-none focus:border-brand";

export function CharacterOptionCard({ characterId, option, canEdit }: { characterId: string; option: CharacterOptionSelection; canEdit: boolean }) {
  const [open, setOpen] = useState(false);
  const [state, setState] = useState<OptionCardState>({});
  const [saving, startSave] = useTransition();
  const [confirmingRemoval, setConfirmingRemoval] = useState(false);
  const [removing, startRemoval] = useTransition();
  const [catalog, setCatalog] = useState({ id: option.characterOptionId ?? "", name: option.nameSnapshot, identity: option.sourceMaterialIdentitySnapshot ?? "", title: option.sourceMaterialTitleSnapshot ?? "", url: option.sourceUrlSnapshot ?? "" });
  const [importUrl, setImportUrl] = useState("");
  const [importError, setImportError] = useState("");
  const [importing, startImport] = useTransition();
  const kindLabel = option.selectionKind === "heritage" ? "Heritage" : option.acquisitionMethod === "awarded" ? "Bonus feat" : option.featCategory ? `${option.featCategory[0]!.toUpperCase()}${option.featCategory.slice(1)} feat` : "Feat";
  const card = <div className="w-full text-left"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="text-xs font-semibold tracking-wide text-text-muted uppercase">{kindLabel}</p><h3 className="mt-1 font-semibold">{option.nameSnapshot}</h3></div><span className={`rounded-full px-2 py-1 text-xs font-semibold ${option.characterOptionId ? "bg-success/10 text-success" : "bg-warning/10 text-warning"}`}>{option.characterOptionId ? "Catalog linked" : "Needs import"}</span></div><p className="mt-2 text-sm text-text-muted">Level {option.acquiredLevel} · {option.acquisitionMethod === "awarded" ? option.grantOrigin ? `Bonus feat · ${option.grantOrigin}` : "Bonus feat · Source unknown" : "Selected"}</p>{option.sourceMaterialTitleSnapshot ? <p className="mt-1 text-sm text-text-muted">Source: {option.sourceMaterialTitleSnapshot}</p> : null}</div>;
  return <li id={`option-${option.id}`} className="scroll-mt-6 target:rounded-xl target:outline-3 target:outline-offset-4 target:outline-brand">{canEdit ? <button type="button" onClick={() => { setState({}); setConfirmingRemoval(false); setOpen(true); }} aria-label={`Edit ${option.nameSnapshot}`} className="w-full rounded-xl border border-border bg-surface-raised p-4 transition-colors hover:border-brand hover:bg-surface-hover focus-visible:outline-3 focus-visible:outline-brand">{card}</button> : <article className="rounded-xl border border-border bg-surface-raised p-4">{card}</article>}
    {open ? <Dialog open title={`Edit ${option.nameSnapshot}`} description="Update this selection or link it to the Archives of Nethys catalog." onClose={() => setOpen(false)} closeLabel={`Close edit ${option.nameSnapshot}`}>
      <form action={(formData) => startSave(async () => { const result = await updateOptionCardAction(characterId, option.id, {}, formData); setState(result); if (result.saved) setOpen(false); })} className="mt-5 space-y-4">
        <input type="hidden" name="selectionKind" value={option.selectionKind} /><input type="hidden" name="characterOptionId" value={catalog.id} /><input type="hidden" name="sourceMaterialIdentity" value={catalog.identity} /><input type="hidden" name="sourceMaterialTitle" value={catalog.title} /><input type="hidden" name="sourceUrl" value={catalog.url} /><input type="hidden" name="sourceChronicleId" value={option.sourceChronicleId ?? ""} />
        <div><label htmlFor={`${option.id}-name`} className="text-sm font-semibold">Name</label><input id={`${option.id}-name`} name="name" required maxLength={200} value={catalog.name} onChange={(event) => setCatalog((value) => ({ ...value, id: "", name: event.currentTarget.value }))} className={inputClass} /></div>
        <div className="grid gap-4 sm:grid-cols-2"><div><label htmlFor={`${option.id}-level`} className="text-sm font-semibold">Acquired level</label><input id={`${option.id}-level`} name="acquiredLevel" type="number" min={1} max={20} required defaultValue={option.acquiredLevel} className={inputClass} /></div>{option.selectionKind === "feat" ? <div><label htmlFor={`${option.id}-category`} className="text-sm font-semibold">Rules category</label><select id={`${option.id}-category`} name="featCategory" defaultValue={option.featCategory ?? ""} className={inputClass}><option value="">Unknown</option>{["class", "ancestry", "skill", "general"].map((value) => <option key={value} value={value}>{value}</option>)}</select></div> : null}</div>
        <fieldset><legend className="text-sm font-semibold">Acquisition</legend><div className="mt-2 flex gap-5">{["selected", "awarded"].map((value) => <label key={value} className="flex items-center gap-2 capitalize"><input type="radio" name="acquisitionMethod" value={value} defaultChecked={(option.acquisitionMethod ?? "selected") === value} />{value}</label>)}</div></fieldset>
        <div><label htmlFor={`${option.id}-origin`} className="text-sm font-semibold">Grant origin <span className="font-normal text-text-muted">(optional)</span></label><input id={`${option.id}-origin`} name="grantOrigin" maxLength={300} defaultValue={option.grantOrigin ?? ""} className={inputClass} /></div>
        <div><label htmlFor={`${option.id}-note`} className="text-sm font-semibold">Validation note <span className="font-normal text-text-muted">(optional)</span></label><textarea id={`${option.id}-note`} name="validationNote" rows={3} maxLength={1000} defaultValue={option.validationNote ?? ""} className={`${inputClass} resize-y`} /></div>
        <OptionCatalogSearch kind={option.selectionKind as "heritage" | "feat"} category={["class", "ancestry", "skill", "general"].includes(option.featCategory ?? "") ? option.featCategory as "class" | "ancestry" | "skill" | "general" : null} onSelected={(selected) => { setCatalog({ id: selected.id, name: selected.name, identity: selected.sourceMaterialIdentity ?? "", title: selected.sourceMaterialTitle ?? "", url: selected.sourceUrl ?? "" }); setImportError(""); }} />
        <section className="rounded-xl border border-border p-4"><h3 className="font-semibold">Import an exact link</h3><p className="mt-1 text-sm text-text-muted">Paste the official Archives of Nethys page to replace the name and source snapshots.</p><div className="mt-3 flex flex-col gap-2 sm:flex-row"><input type="url" aria-label="Archives of Nethys link" value={importUrl} onChange={(event) => setImportUrl(event.currentTarget.value)} className="min-w-0 flex-1 rounded-xl border border-border-strong bg-surface px-3 py-2" /><button type="button" disabled={importing || !importUrl.trim()} onClick={() => startImport(async () => { const result = await importCharacterOptionAction(importUrl, option.selectionKind as "heritage" | "feat"); if (!result.ok) return setImportError(result.error); setCatalog({ id: result.option.id, name: result.option.name, identity: result.option.sourceMaterialIdentity ?? "", title: result.option.sourceMaterialTitle ?? "", url: result.option.sourceUrl ?? "" }); setImportError(""); })} className="rounded-full border border-border-strong px-4 py-2 text-sm font-semibold disabled:opacity-50">{importing ? "Importing…" : "Import link"}</button></div>{importError ? <p role="alert" className="mt-2 text-sm text-danger">{importError}</p> : null}{catalog.id ? <p role="status" className="mt-2 text-sm text-success">Linked to {catalog.title || "the catalog"}.</p> : null}</section>
        {state.error ? <p role="alert" className="text-sm text-danger">{state.error}</p> : null}{confirmingRemoval ? <div role="alert" className="rounded-xl bg-danger/10 p-4"><p className="font-semibold text-danger">Remove {option.nameSnapshot}?</p><p className="mt-1 text-sm text-text-muted">This removes the {option.selectionKind} from this character.</p><div className="mt-3 flex gap-3"><button type="button" disabled={removing} onClick={() => startRemoval(async () => { const result = await deleteOptionCardAction(characterId, option.id); if (result.ok) setOpen(false); else setState({ error: result.error }); })} className="rounded-full bg-danger px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{removing ? "Removing…" : `Yes, remove ${option.selectionKind}`}</button><button type="button" disabled={removing} onClick={() => setConfirmingRemoval(false)} className="rounded-full border border-border-strong px-4 py-2 text-sm font-semibold">Keep {option.selectionKind}</button></div></div> : null}<div className="flex flex-wrap items-center justify-between gap-3 border-t border-border pt-4"><div>{!confirmingRemoval ? <button type="button" onClick={() => setConfirmingRemoval(true)} className="rounded-full px-4 py-2 text-sm font-semibold text-danger hover:bg-danger/10">Remove {option.selectionKind}</button> : null}</div><div className="flex gap-3"><button type="button" onClick={() => setOpen(false)} className="rounded-full border border-border-strong px-4 py-2 font-semibold">Cancel</button><button disabled={saving || removing} className="rounded-full bg-brand px-5 py-2 font-semibold text-on-brand disabled:opacity-60">{saving ? "Saving…" : "Save selection"}</button></div></div>
      </form>
    </Dialog> : null}
  </li>;
}
