import { eq } from "drizzle-orm";
import { afterEach, describe, expect, it } from "vitest";
import { createTestIdentity } from "@/auth/test-fixture";
import { createCharacter, getCharacterDetail, listCharacters, updateCharacter } from "@/character/characters";
import { applyManualChronicle, createManualChronicle, deleteManualChronicle, listChronicles, unapplyManualChronicle, updateManualChronicle } from "@/character/chronicles";
import { createCreditAdjustment, getOwnedCreditLedger } from "@/character/credit-ledger";
import { createInventoryEntry, deleteInventoryEntry, listOwnedInventory, updateInventoryEntry } from "@/character/inventory";
import { getDb } from "@/db/client";
import { authUsers, characterCreditLedgerEntries, characters, gameSystems, people } from "@/db/schema";
import { SUPPORTED_GAME_SYSTEM } from "@/game-system/config";
const describeWithDatabase = process.env.CI ? describe : describe.skip;
const userIds: string[] = [];
const systemIds: string[] = [];
const event = { eventName: "Starfinder Nexus", eventCode: "2,690,298" };
describeWithDatabase("characters persistence", () => {
  afterEach(async () => {
    for (const id of userIds.splice(0)) await getDb().delete(authUsers).where(eq(authUsers.id, id));
    for (const id of systemIds.splice(0)) await getDb().delete(gameSystems).where(eq(gameSystems.id, id));
  });
  it("creates and lists characters only for the authenticated actor", async () => {
    const owner = await createTestIdentity({ name: "Owner", sessions: 0 });
    const other = await createTestIdentity({ name: "Other", sessions: 0 });
    userIds.push(owner.authUser.id, other.authUser.id);
    await getDb().insert(gameSystems).values({ id: SUPPORTED_GAME_SYSTEM.id, code: SUPPORTED_GAME_SYSTEM.code, name: SUPPORTED_GAME_SYSTEM.name }).onConflictDoUpdate({ target: gameSystems.id, set: { code: SUPPORTED_GAME_SYSTEM.code, name: SUPPORTED_GAME_SYSTEM.name } });
    const ownerActor = { personId: owner.person.id, authUserId: owner.authUser.id, sessionId: "owner" };
    const otherActor = { personId: other.person.id, authUserId: other.authUser.id, sessionId: "other" };
    await getDb().update(people).set({ societyPlayNumber: "123456" }).where(eq(people.id, owner.person.id));
    await createCharacter(ownerActor, { name: "Navasi", characterNumber: "01", startingLevel: 3 });
    expect(await listCharacters(ownerActor)).toEqual([expect.objectContaining({ name: "Navasi", societyNumber: "123456-2701", gameSystemName: "Starfinder 2E" })]);
    expect(await listCharacters(otherActor)).toEqual([]);
    expect(await getDb().select().from(characters).where(eq(characters.personId, owner.person.id))).toEqual([
      expect.objectContaining({ gameSystemId: SUPPORTED_GAME_SYSTEM.id, startingLevel: 3 }),
    ]);
  });

  it("updates details only when the actor owns the character", async () => {
    const owner = await createTestIdentity({ name: "Owner", sessions: 0 });
    const other = await createTestIdentity({ name: "Other", sessions: 0 });
    userIds.push(owner.authUser.id, other.authUser.id);
    await getDb().insert(gameSystems).values({ id: SUPPORTED_GAME_SYSTEM.id, code: SUPPORTED_GAME_SYSTEM.code, name: SUPPORTED_GAME_SYSTEM.name }).onConflictDoUpdate({ target: gameSystems.id, set: { code: SUPPORTED_GAME_SYSTEM.code, name: SUPPORTED_GAME_SYSTEM.name } });
    const ownerActor = { personId: owner.person.id, authUserId: owner.authUser.id, sessionId: "owner" };
    const otherActor = { personId: other.person.id, authUserId: other.authUser.id, sessionId: "other" };
    await getDb().update(people).set({ societyPlayNumber: "654321" }).where(eq(people.id, owner.person.id));
    const created = await createCharacter(ownerActor, { name: "Navasi", characterNumber: "01" });
    if (!created) throw new Error("Expected character creation to return a record.");

    expect(await updateCharacter(otherActor, created.id, { name: "Stolen" })).toBeNull();
    const attemptedStartingLevelChange = { name: " Navasi ", startingLevel: 7, className: " Envoy ", ancestry: "Human", background: "  ", backstory: "  Raised aboard a station.  ", notes: "  " } as Parameters<typeof updateCharacter>[2];
    expect(await updateCharacter(ownerActor, created.id, attemptedStartingLevelChange)).toEqual(expect.objectContaining({ id: created.id }));
    expect(await getCharacterDetail(ownerActor, created.id)).toEqual(expect.objectContaining({ name: "Navasi", startingLevel: 1, currentLevel: 1, xp: 0, className: "Envoy", ancestry: "Human", background: null, backstory: "Raised aboard a station.", notes: null, isOwner: true }));
  });

  it("owner-manages manual Chronicles without changing identity", async () => {
    const owner = await createTestIdentity({ name: "Chronicle Owner", sessions: 0 });
    const other = await createTestIdentity({ name: "Chronicle Other", sessions: 0 });
    userIds.push(owner.authUser.id, other.authUser.id);
    await getDb().insert(gameSystems).values({ id: SUPPORTED_GAME_SYSTEM.id, code: SUPPORTED_GAME_SYSTEM.code, name: SUPPORTED_GAME_SYSTEM.name }).onConflictDoUpdate({ target: gameSystems.id, set: { code: SUPPORTED_GAME_SYSTEM.code, name: SUPPORTED_GAME_SYSTEM.name } });
    await getDb().update(people).set({ societyPlayNumber: "777777" }).where(eq(people.id, owner.person.id));
    const ownerActor = { personId: owner.person.id, authUserId: owner.authUser.id, sessionId: "owner" };
    const otherActor = { personId: other.person.id, authUserId: other.authUser.id, sessionId: "other" };
    const character = await createCharacter(ownerActor, { name: "Chronicle Hero", characterNumber: "01" });
    if (!character) throw new Error("Expected character creation.");
    const first = await createManualChronicle(ownerActor, character.id, { ...event, scenarioNumber: "1-02", scenarioName: "Second", datePlayed: "2026-08-20", characterLevel: 1, advancementSpeed: "standard", xp: 4, baseCreditsMinor: 100, downtimeDisposition: "declined" });
    const second = await createManualChronicle(ownerActor, character.id, { ...event, scenarioNumber: "1-01", scenarioName: "First", datePlayed: "2026-08-21", characterLevel: 1, advancementSpeed: "slow", xp: 2, baseCreditsMinor: 50, downtimeDisposition: "declined" });
    if (!first || !second) throw new Error("Expected Chronicle creation.");
    expect(first).toEqual(expect.objectContaining({ status: "pending", appliedAt: null, provenance: "manual", playedOn: "2026-08-20" }));
    expect(await getCharacterDetail(ownerActor, character.id)).toEqual(expect.objectContaining({ xp: 0, creditsMinor: 150 }));
    expect(await createManualChronicle(otherActor, character.id, { ...event, scenarioNumber: "x", scenarioName: "Unauthorized", datePlayed: "2026-08-20", characterLevel: 1, advancementSpeed: "standard", xp: 0, baseCreditsMinor: 0, downtimeDisposition: "declined" })).toBeNull();
    expect((await listChronicles(character.id)).map((entry) => entry.id)).toEqual([second.id, first.id]);
    expect(await updateManualChronicle(otherActor, character.id, first.id, { ...event, scenarioNumber: "x", scenarioName: "Stolen", datePlayed: "2026-08-20", characterLevel: 1, advancementSpeed: "standard", xp: 0, baseCreditsMinor: 0, downtimeDisposition: "declined" })).toBeNull();
    const updated = await updateManualChronicle(ownerActor, character.id, first.id, { ...event, scenarioNumber: "1-02", scenarioName: "Updated snapshot", datePlayed: "2026-08-22", characterLevel: 2, advancementSpeed: "standard", xp: 12, baseCreditsMinor: 225, downtimeDisposition: "declined" });
    expect(updated).toEqual(expect.objectContaining({ id: first.id, scenarioNameSnapshot: "Updated snapshot", baseCreditsMinor: 225 }));
    expect(await applyManualChronicle(otherActor, character.id, first.id)).toBeNull();
    const appliedAt = new Date("2026-08-23T10:00:00Z");
    expect(await applyManualChronicle(ownerActor, character.id, first.id, getDb(), appliedAt)).toEqual(expect.objectContaining({ status: "applied", appliedAt, chronicleNumber: "1" }));
    expect(await applyManualChronicle(ownerActor, character.id, first.id, getDb(), new Date("2026-08-24T10:00:00Z"))).toEqual(expect.objectContaining({ status: "applied", appliedAt, chronicleNumber: "1" }));
    expect(await getCharacterDetail(ownerActor, character.id)).toEqual(expect.objectContaining({ xp: 12, currentLevel: 2, creditsMinor: 375 }));
    expect(await listCharacters(ownerActor)).toEqual([expect.objectContaining({ id: character.id, totalXp: 12, currentLevel: 2 })]);
    expect(await updateManualChronicle(ownerActor, character.id, first.id, { ...event, scenarioNumber: "x", scenarioName: "Applied edit", datePlayed: "2026-08-22", characterLevel: 2, advancementSpeed: "standard", xp: 99, baseCreditsMinor: 250, downtimeDisposition: "declined" })).toEqual(expect.objectContaining({ status: "applied", baseCreditsMinor: 250 }));
    expect(await getCharacterDetail(ownerActor, character.id)).toEqual(expect.objectContaining({ creditsMinor: 400 }));
    expect(await deleteManualChronicle(ownerActor, character.id, first.id)).toBe(false);
    expect(await unapplyManualChronicle(ownerActor, character.id, first.id)).toEqual(expect.objectContaining({ status: "pending", appliedAt: null }));
    expect(await getCharacterDetail(ownerActor, character.id)).toEqual(expect.objectContaining({ xp: 0, creditsMinor: 150 }));
    expect(await deleteManualChronicle(otherActor, character.id, first.id)).toBe(false);
    expect(await deleteManualChronicle(ownerActor, character.id, first.id)).toBe(false);
    expect(await deleteManualChronicle(ownerActor, character.id, second.id)).toBe(true);
    expect((await listChronicles(character.id)).map((entry) => entry.id)).toEqual([first.id]);
    expect(await getOwnedCreditLedger(otherActor, character.id)).toBeNull();
    expect(await createCreditAdjustment(otherActor, character.id, { amountMinor: -25, effectiveOn: "2026-08-24", notes: "Not mine" })).toBeNull();
    expect(await createCreditAdjustment(ownerActor, character.id, { amountMinor: -25, effectiveOn: "2026-08-24", notes: "Purchase correction" })).toEqual(expect.objectContaining({ amountMinor: -25, type: "adjustment", source: "owner_adjustment" }));
    const adjusted = await getOwnedCreditLedger(ownerActor, character.id);
    expect(adjusted?.balanceMinor).toBe(125);
    expect(adjusted?.entries.map(({ amountMinor }) => amountMinor)).toEqual([225, 25, -250, -25, 150]);
    expect(await applyManualChronicle(ownerActor, character.id, first.id)).toEqual(expect.objectContaining({ status: "applied", chronicleNumber: "1" }));
    expect((await getOwnedCreditLedger(ownerActor, character.id))?.balanceMinor).toBe(375);
    expect((await getOwnedCreditLedger(ownerActor, character.id))?.entries.filter(({ type }) => type === "chronicle_reward")).toHaveLength(1);
  });

  it("owner-manages distinct inventory lots without ledger side effects", async () => {
    const owner = await createTestIdentity({ name: "Inventory Owner", sessions: 0 });
    const other = await createTestIdentity({ name: "Inventory Other", sessions: 0 });
    userIds.push(owner.authUser.id, other.authUser.id);
    await getDb().insert(gameSystems).values({ id: SUPPORTED_GAME_SYSTEM.id, code: SUPPORTED_GAME_SYSTEM.code, name: SUPPORTED_GAME_SYSTEM.name }).onConflictDoUpdate({ target: gameSystems.id, set: { code: SUPPORTED_GAME_SYSTEM.code, name: SUPPORTED_GAME_SYSTEM.name } });
    await getDb().update(people).set({ societyPlayNumber: "888888" }).where(eq(people.id, owner.person.id));
    await getDb().update(people).set({ societyPlayNumber: "999999" }).where(eq(people.id, other.person.id));
    const ownerActor = { personId: owner.person.id, authUserId: owner.authUser.id, sessionId: "owner" };
    const otherActor = { personId: other.person.id, authUserId: other.authUser.id, sessionId: "other" };
    const character = await createCharacter(ownerActor, { name: "Equipped Hero", characterNumber: "01" });
    const otherCharacter = await createCharacter(otherActor, { name: "Other Hero", characterNumber: "01" });
    if (!character || !otherCharacter) throw new Error("Expected characters.");
    const source = await createManualChronicle(ownerActor, character.id, { ...event, scenarioNumber: "1-01", scenarioName: "Source", datePlayed: "2026-08-20", characterLevel: 1, advancementSpeed: "standard", xp: 0, baseCreditsMinor: 0, downtimeDisposition: "declined" });
    const wrongSource = await createManualChronicle(otherActor, otherCharacter.id, { ...event, scenarioNumber: "1-02", scenarioName: "Wrong source", datePlayed: "2026-08-20", characterLevel: 1, advancementSpeed: "standard", xp: 0, baseCreditsMinor: 0, downtimeDisposition: "declined" });
    if (!source || !wrongSource) throw new Error("Expected Chronicles.");
    const ledgerBefore = await getDb().select().from(characterCreditLedgerEntries).where(eq(characterCreditLedgerEntries.characterId, character.id));
    const first = await createInventoryEntry(ownerActor, character.id, { itemName: "Laser rifle", quantity: 1, acquisitionType: "purchased", acquiredOn: "2026-08-21", amountPaidMinor: 100, sourceChronicleId: source.id });
    const second = await createInventoryEntry(ownerActor, character.id, { itemName: "Laser rifle", quantity: 2, acquisitionType: "purchased", acquiredOn: "2026-08-21", amountPaidMinor: 125, sourceChronicleId: source.id });
    if (!first || !second) throw new Error("Expected inventory entries.");
    expect(first.lotKey).not.toBe(second.lotKey);
    expect((await listOwnedInventory(ownerActor, character.id))?.map(({ amountPaidMinor }) => amountPaidMinor)).toEqual([100, 125]);
    expect(await listOwnedInventory(otherActor, character.id)).toBeNull();
    expect(await createInventoryEntry(otherActor, character.id, { itemName: "Stolen", quantity: 1, acquisitionType: "other", acquiredOn: "2026-08-21" })).toBeNull();
    await expect(createInventoryEntry(ownerActor, character.id, { itemName: "Bad source", quantity: 1, acquisitionType: "boon_reward", acquiredOn: "2026-08-21", sourceChronicleId: wrongSource.id })).rejects.toThrow("must belong to this character");
    expect(await updateInventoryEntry(otherActor, character.id, first.id, { itemName: "Stolen", quantity: 9, acquisitionType: "other", acquiredOn: "2026-08-22" })).toBeNull();
    expect(await updateInventoryEntry(ownerActor, character.id, first.id, { itemName: "Laser rifle snapshot", quantity: 3, acquisitionType: "purchased", acquiredOn: "2026-08-22", amountPaidMinor: 100 })).toEqual(expect.objectContaining({ quantity: 3, lotKey: first.lotKey }));
    expect(await deleteInventoryEntry(otherActor, character.id, second.id)).toBe(false);
    expect(await deleteInventoryEntry(ownerActor, character.id, second.id)).toBe(true);
    const ledgerAfter = await getDb().select().from(characterCreditLedgerEntries).where(eq(characterCreditLedgerEntries.characterId, character.id));
    expect(ledgerAfter).toEqual(ledgerBefore);
  });
});
