"use client";
import { useState, useTransition } from "react";
import { Dialog } from "@/app/dialog";
import { resolveKnownMaterialAction, resolveMaterialAction } from "@/app/profile/material-actions";
import { materialTitleWithoutCitation } from "@/materials/material-identity";

export function MaterialResolutionActions({ title, identity, onAdded, onAddNote }: { title: string; identity: string; onAdded: (identities: string[]) => void; onAddNote: () => void }) {
  const materialTitle = materialTitleWithoutCitation(title);
  const [open, setOpen] = useState(false); const [url, setUrl] = useState(""); const [message, setMessage] = useState(""); const [pending, startTransition] = useTransition();
  function resolve() { setMessage(""); startTransition(async () => { const result = await resolveKnownMaterialAction(identity, title); if (result.found) { onAdded(result.identities); return; } if (result.error) setMessage(result.error); setOpen(true); }); }
  function add() { setMessage(""); startTransition(async () => { const result = await resolveMaterialAction(url, identity, title); if (!result.ok) { setMessage(result.error); return; } onAdded(result.identities); setUrl(""); setOpen(false); }); }
  return <div className="mt-3 flex flex-wrap gap-3"><button type="button" disabled={pending} className="font-semibold text-brand hover:underline disabled:opacity-60" onClick={resolve}>{pending && !open ? "Checking…" : `Add ${materialTitle}`}</button><button type="button" className="font-semibold text-brand hover:underline" onClick={onAddNote}>Add Note</button>{open ? <Dialog open title={`Add ${materialTitle}`} description="This source is not in the catalog yet. Paste its Archives of Nethys source link or Paizo product link to add it to Materials Owned." onClose={() => setOpen(false)} closeLabel="Close material dialog" className="max-w-lg"><label htmlFor={`material-${identity}`} className="mt-5 block text-sm font-semibold">Source or product link</label><input id={`material-${identity}`} type="url" value={url} onChange={(event) => { setUrl(event.currentTarget.value); setMessage(""); }} autoFocus placeholder="https://2e.aonsrd.com/sources/…" className="mt-2 w-full rounded-xl border border-border-strong bg-surface px-4 py-3 outline-none focus:border-brand" />{message ? <p role="alert" className="mt-3 text-sm text-danger">{message}</p> : null}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setOpen(false)} className="rounded-full border border-border-strong px-4 py-2 font-semibold">Cancel</button><button type="button" onClick={add} disabled={pending || !url.trim()} className="rounded-full bg-brand px-4 py-2 font-semibold text-on-brand disabled:opacity-60">{pending ? "Adding…" : `Add ${materialTitle}`}</button></div></Dialog> : null}</div>;
}
