"use client";
import Link from "next/link";
import { useActionState, useState } from "react";
import { useFormStatus } from "react-dom";
import type { Chronicle } from "@/character/chronicles";
import { calculateEarnIncome, type DowntimeProficiency } from "@/character/sfs2-chronicle-rewards";
import type { ChronicleFormState } from "./actions";

type CatalogItem = { id: string; code: string; title: string };
const inputClass = "mt-2 w-full rounded-xl border border-border-strong bg-surface-raised px-4 py-3 outline-none focus:border-brand";
const standardScenarioCredits: Record<number, number> = { 1: 140, 2: 220, 3: 380, 4: 640, 5: 1000, 6: 1500, 7: 2200, 8: 3000, 9: 4400, 10: 6000 };
function SubmitButton({ editing }: { editing: boolean }) { const { pending } = useFormStatus(); return <button type="submit" disabled={pending} className="rounded-full bg-brand px-6 py-3 font-semibold text-on-brand disabled:opacity-60">{pending ? "Saving…" : editing ? "Save Chronicle" : "Add Chronicle"}</button>; }

export function ChronicleForm({ characterId, chronicle, catalogItems, action }: { characterId: string; chronicle?: Chronicle; catalogItems: CatalogItem[]; action: (state: ChronicleFormState, formData: FormData) => Promise<ChronicleFormState> }) {
  const [state, formAction] = useActionState(action, {});
  const [scenarioNumber, setScenarioNumber] = useState(chronicle?.scenarioNumberSnapshot ?? "");
  const [scenarioName, setScenarioName] = useState(chronicle?.scenarioNameSnapshot ?? "");
  const [characterLevel, setCharacterLevel] = useState(String(chronicle?.characterLevel ?? 1));
  const [advancementSpeed, setAdvancementSpeed] = useState<"standard" | "slow">(chronicle?.advancementSpeed === "slow" ? "slow" : "standard");
  const [xp, setXp] = useState(chronicle?.xp ?? 4);
  const [baseCredits, setBaseCredits] = useState(chronicle?.baseCreditsMinor ?? 140);
  const [disposition, setDisposition] = useState(chronicle?.downtimeDisposition ?? "declined");
  const [entryMethod, setEntryMethod] = useState<"calculated" | "sheet">(chronicle?.downtimeEntryMethod === "sheet" ? "sheet" : "calculated");
  const [checkTotal, setCheckTotal] = useState(chronicle?.downtimeCheckTotal == null ? "" : String(chronicle.downtimeCheckTotal));
  const [proficiency, setProficiency] = useState<DowntimeProficiency>((chronicle?.downtimeProficiency as DowntimeProficiency | null) ?? "trained");
  const [sheetCredits, setSheetCredits] = useState(chronicle?.downtimeSheetCreditsMinor == null ? "" : String(chronicle.downtimeSheetCreditsMinor));
  const [correctionCredits, setCorrectionCredits] = useState(chronicle?.downtimeOverrideCreditsMinor == null ? "" : String(chronicle.downtimeOverrideCreditsMinor));
  const updateDefaults = (level: number, speed: "standard" | "slow") => { const divisor = speed === "slow" ? 2 : 1; setXp(4 / divisor); setBaseCredits((standardScenarioCredits[level] ?? 0) / divisor); };
  const field = (name: string) => state.fieldErrors?.[name]?.[0];
  const error = (name: string) => field(name) ? <p role="alert" className="mt-2 text-sm text-danger">{field(name)}</p> : null;
  const level = Number(characterLevel);
  const calculated = disposition === "earn_income" && entryMethod === "calculated" && checkTotal !== "" && level >= 1 && level <= 10 ? calculateEarnIncome(level, Number(checkTotal), proficiency, xp * 2) : null;
  const downtimeTotal = correctionCredits !== "" ? Number(correctionCredits) : entryMethod === "sheet" ? Number(sheetCredits || 0) : calculated?.calculatedCreditsMinor ?? 0;
  return <form action={formAction} className="mt-10 space-y-6" noValidate>
    <div><label htmlFor="contentItemId" className="block text-sm font-semibold">Catalog scenario <span className="font-normal text-text-muted">(optional)</span></label><select id="contentItemId" name="contentItemId" defaultValue={chronicle?.contentItemId ?? ""} onChange={(event) => { const item = catalogItems.find((candidate) => candidate.id === event.target.value); if (item) { setScenarioNumber(item.code); setScenarioName(item.title); } }} className={inputClass}><option value="">Manually enter the scenario</option>{catalogItems.map((item) => <option key={item.id} value={item.id}>{item.code} — {item.title}</option>)}</select><p className="mt-2 text-xs text-text-muted">Selecting a catalog scenario fills the number and name and stores them as a permanent snapshot.</p></div>
    <div className="grid gap-5 sm:grid-cols-2">
      <div><label htmlFor="scenarioNumber" className="block text-sm font-semibold">Scenario number</label><input id="scenarioNumber" name="scenarioNumber" required maxLength={100} value={scenarioNumber} onChange={(event) => setScenarioNumber(event.target.value)} aria-invalid={Boolean(field("scenarioNumber"))} className={inputClass} />{error("scenarioNumber")}</div>
      <div><label htmlFor="scenarioName" className="block text-sm font-semibold">Scenario name</label><input id="scenarioName" name="scenarioName" required maxLength={200} value={scenarioName} onChange={(event) => setScenarioName(event.target.value)} aria-invalid={Boolean(field("scenarioName"))} className={inputClass} />{error("scenarioName")}</div>
      <div><label htmlFor="datePlayed" className="block text-sm font-semibold">Date played</label><input id="datePlayed" name="datePlayed" type="date" required max={new Date().toISOString().slice(0, 10)} defaultValue={chronicle?.playedOn ?? ""} aria-invalid={Boolean(field("datePlayed"))} className={inputClass} />{error("datePlayed")}</div>
      <div><label htmlFor="characterLevel" className="block text-sm font-semibold">Character level at play</label><input id="characterLevel" name="characterLevel" type="number" min={1} max={20} required value={characterLevel} onChange={(event) => { setCharacterLevel(event.target.value); updateDefaults(Number(event.target.value), advancementSpeed); }} className={inputClass} />{error("characterLevel")}</div>
      <div><label htmlFor="advancementSpeed" className="block text-sm font-semibold">Advancement speed</label><select id="advancementSpeed" name="advancementSpeed" value={advancementSpeed} onChange={(event) => { const speed = event.target.value as "standard" | "slow"; setAdvancementSpeed(speed); updateDefaults(Number(characterLevel), speed); }} className={inputClass}><option value="standard">Standard</option><option value="slow">Slow</option></select>{error("advancementSpeed")}</div>
      <div><label htmlFor="xp" className="block text-sm font-semibold">XP</label><input id="xp" name="xp" type="number" min={0} step={1} required value={xp} onChange={(event) => setXp(Number(event.target.value))} className={inputClass} />{error("xp")}<p className="mt-2 text-xs text-text-muted">{xp * 2} Downtime days, resolved when applied.</p></div>
      <div><label htmlFor="baseCreditsMinor" className="block text-sm font-semibold">Base adventure credits</label><input id="baseCreditsMinor" name="baseCreditsMinor" type="number" min={0} step={1} required value={baseCredits} onChange={(event) => setBaseCredits(Number(event.target.value))} className={inputClass} />{error("baseCreditsMinor")}</div>
      <div><label htmlFor="downtimeDisposition" className="block text-sm font-semibold">Downtime disposition</label><select id="downtimeDisposition" name="downtimeDisposition" value={disposition} onChange={(event) => setDisposition(event.target.value)} className={inputClass}><option value="earn_income">Earn Income</option><option value="other">Another activity</option><option value="declined">Declined / lost</option></select>{error("downtimeDisposition")}</div>
      {disposition === "earn_income" ? <>
        <div className="sm:col-span-2"><fieldset><legend className="block text-sm font-semibold">Earn Income entry</legend><div className="mt-3 flex flex-wrap gap-5"><label className="flex cursor-pointer items-center gap-2"><input className="size-4 shrink-0 appearance-none rounded-full border-2 border-border-strong bg-surface transition checked:border-4 checked:border-brand checked:bg-on-brand focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand" type="radio" name="downtimeEntryMethod" value="calculated" checked={entryMethod === "calculated"} onChange={() => setEntryMethod("calculated")} /> Calculate from my check</label><label className="flex cursor-pointer items-center gap-2"><input className="size-4 shrink-0 appearance-none rounded-full border-2 border-border-strong bg-surface transition checked:border-4 checked:border-brand checked:bg-on-brand focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand" type="radio" name="downtimeEntryMethod" value="sheet" checked={entryMethod === "sheet"} onChange={() => setEntryMethod("sheet")} /> Enter credits from a physical Chronicle</label></div></fieldset></div>
        {entryMethod === "calculated" ? <><div><label htmlFor="downtimeCheckTotal" className="block text-sm font-semibold">Earn Income check total</label><input id="downtimeCheckTotal" name="downtimeCheckTotal" type="number" step={1} required value={checkTotal} onChange={(event) => setCheckTotal(event.target.value)} className={inputClass} />{error("downtimeCheckTotal")}</div><div><label htmlFor="downtimeProficiency" className="block text-sm font-semibold">Proficiency</label><select id="downtimeProficiency" name="downtimeProficiency" value={proficiency} onChange={(event) => setProficiency(event.target.value as DowntimeProficiency)} className={inputClass}><option value="trained">Trained</option><option value="expert">Expert</option><option value="master">Master</option></select></div></> : <div className="sm:col-span-2"><label htmlFor="downtimeSheetCreditsMinor" className="block text-sm font-semibold">Downtime credits from Chronicle sheet</label><input id="downtimeSheetCreditsMinor" name="downtimeSheetCreditsMinor" type="number" min={0} step={1} required value={sheetCredits} onChange={(event) => setSheetCredits(event.target.value)} className={inputClass} />{error("downtimeSheetCreditsMinor")}</div>}
        <div className="sm:col-span-2 rounded-xl border border-border-strong bg-surface-raised p-4" aria-live="polite"><p className="text-sm font-semibold">Chronicle credit total</p>{calculated ? <p className="mt-1 text-sm text-text-muted">Check {checkTotal} vs. DC {calculated.dc}: {calculated.degree.replaceAll("_", " ")} · Earn Income {calculated.calculatedCreditsMinor} credits</p> : null}<p className="mt-2 text-xl font-semibold">{baseCredits + downtimeTotal} credits</p><p className="mt-1 text-xs text-text-muted">{baseCredits} adventure + {downtimeTotal} Downtime</p></div>
        <div><label htmlFor="downtimeOverrideCreditsMinor" className="block text-sm font-semibold">Downtime credits correction <span className="font-normal text-text-muted">(optional)</span></label><input id="downtimeOverrideCreditsMinor" name="downtimeOverrideCreditsMinor" type="number" min={0} step={1} value={correctionCredits} onChange={(event) => setCorrectionCredits(event.target.value)} className={inputClass} /></div><div><label htmlFor="downtimeCorrectionNote" className="block text-sm font-semibold">Correction note</label><input id="downtimeCorrectionNote" name="downtimeCorrectionNote" maxLength={1000} defaultValue={chronicle?.downtimeCorrectionNote ?? ""} className={inputClass} />{error("downtimeCorrectionNote")}</div>
      </> : null}
      {disposition === "other" ? <div><label htmlFor="downtimeActivity" className="block text-sm font-semibold">Downtime activity</label><input id="downtimeActivity" name="downtimeActivity" required maxLength={200} defaultValue={chronicle?.downtimeActivity ?? ""} className={inputClass} /></div> : null}
      <div><p className="block text-sm font-semibold">Character Chronicle number</p><p className={`${inputClass} text-text-muted`}>{chronicle?.chronicleNumber ?? "Generated when applied"}</p></div>
      {[['partnerCode','Partner Code',false],['eventName','Event name',true],['eventCode','Event number / code',true],['gmOrganizedPlayId','GM Organized Play ID',false]].map(([name,label,required]) => <div key={String(name)}><label htmlFor={String(name)} className="block text-sm font-semibold">{label} {!required ? <span className="font-normal text-text-muted">(optional)</span> : null}</label><input id={String(name)} name={String(name)} required={Boolean(required)} maxLength={name === 'eventName' ? 200 : 100} defaultValue={chronicle?.[name as keyof Chronicle] as string ?? ""} aria-invalid={Boolean(field(String(name)))} className={inputClass} />{error(String(name))}</div>)}
      <div className="sm:col-span-2"><label htmlFor="playerNotes" className="block text-sm font-semibold">Player notes <span className="font-normal text-text-muted">(optional)</span></label><textarea id="playerNotes" name="playerNotes" rows={6} maxLength={5000} defaultValue={chronicle?.playerNotes ?? ""} className={`${inputClass} resize-y`} />{error("playerNotes")}</div>
    </div>
    {state.formError ? <p role="alert" className="rounded-xl bg-danger/10 p-4 text-danger">{state.formError}</p> : null}
    <div className="flex items-center gap-4"><SubmitButton editing={Boolean(chronicle)} /><Link href={`/characters/${characterId}?tab=chronicles`} className="text-sm text-text-muted hover:text-text-primary">Cancel</Link></div>
  </form>;
}
