"use client";
import Link from "next/link";
import { useActionState, useEffect, useRef, useState } from "react";
import { useFormStatus } from "react-dom";
import type { Chronicle } from "@/character/chronicles";
import { calculateEarnIncome, type DowntimeProficiency } from "@/character/sfs2-chronicle-rewards";
import { defaultPregenLevel, SFS2_PREGEN_LEVELS } from "@/character/sfs2-pregens";
import type { ChronicleFormState } from "./actions";
import { groupScenarioOptions, ScenarioSelector, type ScenarioLookupState } from "@/app/scenario-selector";

type CatalogItem = { id: string; code: string; title: string; minimumLevel: number; maximumLevel: number };
const inputClass = "mt-2 w-full rounded-xl border border-border-strong bg-surface-raised px-4 py-3 outline-none focus:border-brand";
const standardScenarioCredits: Record<number, number> = { 1: 140, 2: 220, 3: 380, 4: 640, 5: 1000, 6: 1500, 7: 2200, 8: 3000, 9: 4400, 10: 6000 };
function SubmitButton({ editing }: { editing: boolean }) { const { pending } = useFormStatus(); return <button type="submit" disabled={pending} className="rounded-full bg-brand px-6 py-3 font-semibold text-on-brand disabled:opacity-60">{pending ? "Saving…" : editing ? "Save Chronicle" : "Add Chronicle"}</button>; }
function localDate(date: Date) { const year = date.getFullYear(); const month = String(date.getMonth() + 1).padStart(2, "0"); const day = String(date.getDate()).padStart(2, "0"); return `${year}-${month}-${day}`; }
function latestManualPlayDate() { return localDate(new Date()); }

export function ChronicleForm({ characterId, chronicle, catalogItems, action, previewScenario, addScenario }: { characterId: string; chronicle?: Chronicle; catalogItems: CatalogItem[]; action: (state: ChronicleFormState, formData: FormData) => Promise<ChronicleFormState>; previewScenario: (url: string) => Promise<ScenarioLookupState>; addScenario: (url: string) => Promise<ScenarioLookupState> }) {
  const [state, formAction] = useActionState(action, {});
  const initial = (name: string, fallback: string) => state.values?.[name] ?? fallback;
  const formRef = useRef<HTMLFormElement>(null);
  const [scenarioNumber, setScenarioNumber] = useState(initial("scenarioNumber", chronicle?.scenarioNumberSnapshot ?? ""));
  const [scenarioName, setScenarioName] = useState(initial("scenarioName", chronicle?.scenarioNameSnapshot ?? ""));
  const [contentItemId, setContentItemId] = useState(initial("contentItemId", chronicle?.contentItemId ?? ""));
  const [characterLevel, setCharacterLevel] = useState(initial("characterLevel", String(chronicle?.characterLevel ?? 1)));
  const [creditType, setCreditType] = useState<"normal" | "pregen" | "gm" | "correction">(initial("creditType", (chronicle?.creditType as "normal" | "pregen" | "gm" | "correction" | undefined) ?? "normal") as "normal" | "pregen" | "gm" | "correction");
  const [advancementSpeed, setAdvancementSpeed] = useState<"standard" | "slow">(initial("advancementSpeed", chronicle?.advancementSpeed === "slow" ? "slow" : "standard") as "standard" | "slow");
  const [xp, setXp] = useState(Number(initial("xp", String(chronicle?.xp ?? 4))));
  const [baseCredits, setBaseCredits] = useState(Number(initial("baseCreditsMinor", String(chronicle?.baseCreditsMinor ?? 140))));
  const [disposition, setDisposition] = useState(initial("downtimeDisposition", chronicle?.downtimeDisposition ?? "declined"));
  const [entryMethod, setEntryMethod] = useState<"calculated" | "sheet">(initial("downtimeEntryMethod", chronicle?.downtimeEntryMethod === "sheet" ? "sheet" : "calculated") as "calculated" | "sheet");
  const [checkTotal, setCheckTotal] = useState(initial("downtimeCheckTotal", chronicle?.downtimeCheckTotal == null ? "" : String(chronicle.downtimeCheckTotal)));
  const [proficiency, setProficiency] = useState<DowntimeProficiency>(initial("downtimeProficiency", (chronicle?.downtimeProficiency as DowntimeProficiency | null) ?? "trained") as DowntimeProficiency);
  const [sheetCredits, setSheetCredits] = useState(initial("downtimeSheetCreditsMinor", chronicle?.downtimeSheetCreditsMinor == null ? "" : String(chronicle.downtimeSheetCreditsMinor)));
  const [correctionCredits, setCorrectionCredits] = useState(initial("downtimeOverrideCreditsMinor", chronicle?.downtimeOverrideCreditsMinor == null ? "" : String(chronicle.downtimeOverrideCreditsMinor)));
  const updateDefaults = (level: number, speed: "standard" | "slow") => { const divisor = speed === "slow" ? 2 : 1; setXp(4 / divisor); setBaseCredits((standardScenarioCredits[level] ?? 0) / divisor); };
  const field = (name: string) => state.fieldErrors?.[name]?.[0];
  const submitted = (name: string, fallback = "") => state.values?.[name] ?? fallback;
  const error = (name: string) => field(name) ? <p role="alert" className="mt-2 text-sm text-danger">{field(name)}</p> : null;
  const level = Number(characterLevel);
  const selectedScenario = catalogItems.find((item) => item.id === contentItemId);
  const outOfRange = selectedScenario && (level < selectedScenario.minimumLevel || level > selectedScenario.maximumLevel);
  const unavailablePregenLevel = creditType === "pregen" && !SFS2_PREGEN_LEVELS.some((availableLevel) => availableLevel === level);
  const setPregenDefault = (scenario = selectedScenario) => { const nextLevel = defaultPregenLevel(scenario?.minimumLevel, scenario?.maximumLevel); setCharacterLevel(String(nextLevel)); updateDefaults(nextLevel, advancementSpeed); };
  const calculated = disposition === "earn_income" && entryMethod === "calculated" && checkTotal !== "" && level >= 1 && level <= 10 ? calculateEarnIncome(level, Number(checkTotal), proficiency, xp * 2) : null;
  const downtimeTotal = correctionCredits !== "" ? Number(correctionCredits) : entryMethod === "sheet" ? Number(sheetCredits || 0) : calculated?.calculatedCreditsMinor ?? 0;
  useEffect(() => {
    const firstError = Object.keys(state.fieldErrors ?? {})[0];
    if (!firstError) return;
    const namedControl = formRef.current?.elements.namedItem(firstError);
    const control = namedControl instanceof RadioNodeList ? namedControl[0] : namedControl;
    if (!(control instanceof HTMLElement)) return;
    control.focus({ preventScroll: true });
    control.scrollIntoView({ behavior: "smooth", block: "center" });
  }, [state.fieldErrors]);
  return <form ref={formRef} action={formAction} className="mt-10 space-y-6" noValidate>
    <ScenarioSelector groups={groupScenarioOptions(catalogItems)} value={contentItemId} invalid={Boolean(field("contentItemId"))} previewScenario={previewScenario} addScenario={addScenario} onValueChange={(id, item) => { setContentItemId(id); if (item) { setScenarioNumber(item.code); setScenarioName(item.title); if (creditType === "pregen") setPregenDefault(item as CatalogItem); } else { setScenarioNumber(""); setScenarioName(""); } }} />
    <input type="hidden" name="scenarioNumber" value={scenarioNumber} />
    <input type="hidden" name="scenarioName" value={scenarioName} />
    {error("contentItemId")}
    <p className="text-xs text-text-muted">The selected catalog scenario’s number, title, and level range are stored as a permanent Chronicle snapshot.</p>
    <div className="grid gap-5 sm:grid-cols-2">
      <div><label htmlFor="datePlayed" className="block text-sm font-semibold">Date played</label><input id="datePlayed" name="datePlayed" type="date" required max={latestManualPlayDate()} defaultValue={submitted("datePlayed", chronicle?.playedOn ?? "")} aria-invalid={Boolean(field("datePlayed"))} className={inputClass} />{error("datePlayed")}<p className="mt-2 text-xs text-text-muted">Manual Chronicles can only record games played today or earlier.</p></div>
      <div><label htmlFor="timePlayed" className="block text-sm font-semibold">Time played <span className="font-normal text-text-muted">(optional)</span></label><input id="timePlayed" name="timePlayed" type="time" defaultValue={submitted("timePlayed", chronicle?.playedAt ? new Date(chronicle.playedAt).toISOString().slice(11, 16) : "")} aria-invalid={Boolean(field("timePlayed"))} className={inputClass} />{error("timePlayed")}<p className="mt-2 text-xs text-text-muted">Used to order multiple Chronicles recorded on the same date.</p></div>
      <div><label htmlFor="characterLevel" className="block text-sm font-semibold">Level used to earn the Chronicle</label><input id="characterLevel" name="characterLevel" type="number" min={1} max={20} list={creditType === "pregen" ? "pregen-levels" : undefined} required value={characterLevel} onChange={(event) => { setCharacterLevel(event.target.value); updateDefaults(Number(event.target.value), advancementSpeed); }} aria-invalid={Boolean(field("characterLevel") || (creditType === "pregen" && (outOfRange || unavailablePregenLevel)))} className={inputClass} />{creditType === "pregen" ? <datalist id="pregen-levels">{SFS2_PREGEN_LEVELS.map((pregenLevel) => <option key={pregenLevel} value={pregenLevel} />)}</datalist> : null}{error("characterLevel")}<p className="mt-2 text-xs text-text-muted">For pregen play, this defaults to the published Iconic Pregen level for the scenario and remains editable. Available levels are 1, 3, 5, and 7. For GM credit, enter the assigned character’s current level.</p></div>
      <div><label htmlFor="creditType" className="block text-sm font-semibold">How this Chronicle was earned</label><select id="creditType" name="creditType" value={creditType} onChange={(event) => { const nextType = event.target.value as typeof creditType; setCreditType(nextType); if (nextType === "pregen") setPregenDefault(); }} className={inputClass}><option value="normal">Played this character</option><option value="pregen">Played a pregenerated character</option><option value="gm">GM credit assigned to this character</option><option value="correction">Authorized correction</option></select>{error("creditType")}</div>
      {outOfRange ? <div className="sm:col-span-2 rounded-xl border border-warning bg-warning/10 p-4" role="alert"><p className="font-semibold">Level-range warning</p><p className="mt-1 text-sm">{selectedScenario.code} is for levels {selectedScenario.minimumLevel}–{selectedScenario.maximumLevel}; the entered earning level is {level}. {creditType === "normal" ? "Normal character play cannot be applied." : creditType === "pregen" ? "Choose a pregen whose level is within the scenario range." : creditType === "correction" ? "An authorized correction can be applied with an explanation." : "The application service will apply the level-1 recipient exception or hold this GM Chronicle until the required level, as appropriate."}</p></div> : null}
      {creditType === "correction" ? <div className="sm:col-span-2"><label htmlFor="eligibilityNote" className="block text-sm font-semibold">Correction authorization</label><textarea id="eligibilityNote" name="eligibilityNote" required maxLength={1000} defaultValue={submitted("eligibilityNote", chronicle?.eligibilityNote ?? "")} className={`${inputClass} resize-y`} />{error("eligibilityNote")}</div> : <input type="hidden" name="eligibilityNote" value="" />}
      <div><label htmlFor="advancementSpeed" className="block text-sm font-semibold">Advancement speed</label><select id="advancementSpeed" name="advancementSpeed" value={advancementSpeed} onChange={(event) => { const speed = event.target.value as "standard" | "slow"; setAdvancementSpeed(speed); updateDefaults(Number(characterLevel), speed); }} className={inputClass}><option value="standard">Standard</option><option value="slow">Slow</option></select>{error("advancementSpeed")}</div>
      <div><label htmlFor="xp" className="block text-sm font-semibold">XP</label><input id="xp" name="xp" type="number" min={0} step={1} required value={xp} onChange={(event) => setXp(Number(event.target.value))} className={inputClass} />{error("xp")}<p className="mt-2 text-xs text-text-muted">{xp * 2} Downtime days, resolved when applied.</p></div>
      <div><label htmlFor="baseCreditsMinor" className="block text-sm font-semibold">Base adventure credits</label><input id="baseCreditsMinor" name="baseCreditsMinor" type="number" min={0} step={1} required value={baseCredits} onChange={(event) => setBaseCredits(Number(event.target.value))} className={inputClass} />{error("baseCreditsMinor")}</div>
      <div><label htmlFor="downtimeDisposition" className="block text-sm font-semibold">Downtime disposition</label><select id="downtimeDisposition" name="downtimeDisposition" value={disposition} onChange={(event) => setDisposition(event.target.value)} className={inputClass}><option value="earn_income">Earn Income</option><option value="other">Another activity</option><option value="declined">Declined / lost</option></select>{error("downtimeDisposition")}</div>
      {disposition === "earn_income" ? <>
        <div className="sm:col-span-2"><fieldset><legend className="block text-sm font-semibold">Earn Income entry</legend><div className="mt-3 flex flex-wrap gap-5"><label className="flex cursor-pointer items-center gap-2"><input className="size-4 shrink-0 appearance-none rounded-full border-2 border-border-strong bg-surface transition checked:border-4 checked:border-brand checked:bg-on-brand focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand" type="radio" name="downtimeEntryMethod" value="calculated" checked={entryMethod === "calculated"} onChange={() => setEntryMethod("calculated")} /> Calculate from my check</label><label className="flex cursor-pointer items-center gap-2"><input className="size-4 shrink-0 appearance-none rounded-full border-2 border-border-strong bg-surface transition checked:border-4 checked:border-brand checked:bg-on-brand focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand" type="radio" name="downtimeEntryMethod" value="sheet" checked={entryMethod === "sheet"} onChange={() => setEntryMethod("sheet")} /> Enter credits from a physical Chronicle</label></div></fieldset></div>
        {entryMethod === "calculated" ? <><div><label htmlFor="downtimeCheckTotal" className="block text-sm font-semibold">Earn Income check total</label><input id="downtimeCheckTotal" name="downtimeCheckTotal" type="number" step={1} required value={checkTotal} onChange={(event) => setCheckTotal(event.target.value)} className={inputClass} />{error("downtimeCheckTotal")}</div><div><label htmlFor="downtimeProficiency" className="block text-sm font-semibold">Proficiency</label><select id="downtimeProficiency" name="downtimeProficiency" value={proficiency} onChange={(event) => setProficiency(event.target.value as DowntimeProficiency)} className={inputClass}><option value="trained">Trained</option><option value="expert">Expert</option><option value="master">Master</option></select></div></> : <div className="sm:col-span-2"><label htmlFor="downtimeSheetCreditsMinor" className="block text-sm font-semibold">Downtime credits from Chronicle sheet</label><input id="downtimeSheetCreditsMinor" name="downtimeSheetCreditsMinor" type="number" min={0} step={1} required value={sheetCredits} onChange={(event) => setSheetCredits(event.target.value)} className={inputClass} />{error("downtimeSheetCreditsMinor")}</div>}
        <div className="sm:col-span-2 rounded-xl border border-border-strong bg-surface-raised p-4" aria-live="polite"><p className="text-sm font-semibold">Chronicle credit total</p>{calculated ? <p className="mt-1 text-sm text-text-muted">Check {checkTotal} vs. DC {calculated.dc}: {calculated.degree.replaceAll("_", " ")} · Earn Income {calculated.calculatedCreditsMinor} credits</p> : null}<p className="mt-2 text-xl font-semibold">{baseCredits + downtimeTotal} credits</p><p className="mt-1 text-xs text-text-muted">{baseCredits} adventure + {downtimeTotal} Downtime</p></div>
        <div><label htmlFor="downtimeOverrideCreditsMinor" className="block text-sm font-semibold">Downtime credits correction <span className="font-normal text-text-muted">(optional)</span></label><input id="downtimeOverrideCreditsMinor" name="downtimeOverrideCreditsMinor" type="number" min={0} step={1} value={correctionCredits} onChange={(event) => setCorrectionCredits(event.target.value)} className={inputClass} /></div><div><label htmlFor="downtimeCorrectionNote" className="block text-sm font-semibold">Correction note</label><input id="downtimeCorrectionNote" name="downtimeCorrectionNote" maxLength={1000} defaultValue={submitted("downtimeCorrectionNote", chronicle?.downtimeCorrectionNote ?? "")} className={inputClass} />{error("downtimeCorrectionNote")}</div>
      </> : null}
      {disposition === "other" ? <div><label htmlFor="downtimeActivity" className="block text-sm font-semibold">Downtime activity</label><input id="downtimeActivity" name="downtimeActivity" required maxLength={200} defaultValue={submitted("downtimeActivity", chronicle?.downtimeActivity ?? "")} className={inputClass} /></div> : null}
      {[['eventName','Event name',true],['eventCode','Event number / code',true],['gmOrganizedPlayId','GM Organized Play ID',false]].map(([name,label,required]) => <div key={String(name)}><label htmlFor={String(name)} className="block text-sm font-semibold">{label} {!required ? <span className="font-normal text-text-muted">(optional)</span> : null}</label><input id={String(name)} name={String(name)} required={Boolean(required)} maxLength={name === 'eventName' ? 200 : 100} defaultValue={submitted(String(name), chronicle?.[name as keyof Chronicle] as string ?? "")} aria-invalid={Boolean(field(String(name)))} className={inputClass} />{error(String(name))}</div>)}
      <div className="sm:col-span-2"><label htmlFor="playerNotes" className="block text-sm font-semibold">Player notes <span className="font-normal text-text-muted">(optional)</span></label><textarea id="playerNotes" name="playerNotes" rows={6} maxLength={5000} defaultValue={submitted("playerNotes", chronicle?.playerNotes ?? "")} className={`${inputClass} resize-y`} />{error("playerNotes")}</div>
    </div>
    {state.formError ? <p role="alert" className="rounded-xl bg-danger/10 p-4 text-danger">{state.formError}</p> : null}
    <div className="flex items-center gap-4"><SubmitButton editing={Boolean(chronicle)} /><Link href={`/characters/${characterId}?tab=chronicles`} className="text-sm text-text-muted hover:text-text-primary">Cancel</Link></div>
  </form>;
}
