"use client";
import { useActionState, useMemo, useState } from "react";
import { Dialog } from "@/app/dialog";
import { StyledSelect } from "@/app/styled-select";
import { addCatalogMaterialAction, addMaterialAction, type MaterialActionState } from "./material-actions";

type Material = { id: string; title: string; productCode: string | null; sourceUrl: string; isDefault: boolean; isbn?: string | null };
type CatalogMaterial = { id: string; title: string; productCode: string | null; isbn: string | null; paizoProductUrl: string };

export function MaterialsOwned({ materials, catalog, removeAction }: { materials: Material[]; catalog: CatalogMaterial[]; removeAction: (id: string) => Promise<void> }) {
  const [modalOpen, setModalOpen] = useState(false);
  const [selectedId, setSelectedId] = useState("");
  const available = useMemo(() => { const owned = new Set(materials.flatMap((material) => [material.isbn, material.productCode]).filter(Boolean)); return catalog.filter((material) => !owned.has(material.isbn) && !owned.has(material.productCode)); }, [catalog, materials]);
  const catalogOptions = [{ value: "", label: available.length ? "Choose a cataloged source" : "No cataloged sources available", disabled: true }, ...available.map((material) => ({ value: material.id, label: material.title, description: material.productCode ?? `ISBN ${material.isbn}` }))];
  const [catalogState, catalogAction, catalogPending] = useActionState<MaterialActionState, FormData>(async (state, data) => { const result = await addCatalogMaterialAction(state, data); if (result.added) setSelectedId(""); return result; }, {});
  const [paizoState, paizoAction, paizoPending] = useActionState<MaterialActionState, FormData>(async (state, data) => { const result = await addMaterialAction(state, data); if (result.added) setModalOpen(false); return result; }, {});

  return <section><h2 className="text-2xl font-semibold">Materials owned</h2><p className="mt-1 text-sm text-text-muted">Nexus uses these sources to advise whether imported character options are available to you.</p>
    <ul className="mt-5 divide-y divide-border border-b border-border">{materials.map((material) => <li key={material.id} className="flex items-center justify-between gap-4 py-4"><div><a href={material.sourceUrl} target="_blank" rel="noreferrer" className="font-semibold text-brand hover:underline">{material.title}</a><p className="mt-1 text-xs text-text-muted">{material.productCode ?? "Paizo product"}{material.isDefault ? " · Included for every player" : ""}</p></div>{material.isDefault ? <span className="rounded-full border border-success/30 px-3 py-1 text-xs text-success">Default</span> : <form action={() => removeAction(material.id)}><button className="text-sm font-semibold text-danger hover:underline">Remove</button></form>}</li>)}</ul>
    <div className="mt-5 rounded-2xl border border-border bg-surface-raised p-4"><h3 className="font-semibold">Add from source catalog</h3><p className="mt-1 text-sm text-text-muted">Choose a source Nexus already recognizes.</p><form action={catalogAction} className="mt-3 flex items-end gap-3"><div className="min-w-0 flex-1"><StyledSelect name="sourceMaterialId" label="Cataloged source material" value={selectedId} onValueChange={setSelectedId} options={catalogOptions} disabled={!available.length} /></div><button disabled={catalogPending || !selectedId} className="min-h-12 shrink-0 rounded-full bg-brand px-5 py-2.5 font-semibold text-on-brand disabled:opacity-60">{catalogPending ? "Adding…" : "Add"}</button></form>{catalogState.error ? <p role="alert" className="mt-2 text-sm text-danger">{catalogState.error}</p> : null}{catalogState.added ? <p role="status" className="mt-2 text-sm text-success">Material added.</p> : null}</div>
    <button type="button" onClick={() => setModalOpen(true)} className="mt-4 rounded-full border border-brand px-5 py-2.5 font-semibold text-brand hover:bg-brand/5">Add source material</button>
    {modalOpen ? <Dialog open title="Add source material" description="Paste an official Paizo product URL. Nexus will read its title, SKU, and ISBN and add it to Materials Owned." onClose={() => setModalOpen(false)} closeLabel="Close source material dialog" className="max-w-lg"><form action={paizoAction} className="mt-5"><label htmlFor="material-source-url" className="text-sm font-semibold">Paizo product link</label><input id="material-source-url" name="sourceUrl" type="url" required autoFocus placeholder="https://store.paizo.com/product-name/" className="mt-2 w-full rounded-xl border border-border-strong bg-surface-raised px-4 py-3 outline-none focus:border-brand"/>{paizoState.error ? <p role="alert" className="mt-2 text-sm text-danger">{paizoState.error}</p> : null}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setModalOpen(false)} className="rounded-full border border-border-strong px-4 py-2 font-semibold">Cancel</button><button disabled={paizoPending} className="rounded-full bg-brand px-5 py-2 font-semibold text-on-brand disabled:opacity-60">{paizoPending ? "Adding…" : "Add source material"}</button></div></form></Dialog> : null}
  </section>;
}
