"use client";
import { useState, useTransition } from "react";
import { Dialog } from "@/app/dialog";
import { StyledSelect } from "@/app/styled-select";
import { importCharacterOptionAction } from "./character-options-actions";

export type CharacterOptionDraft = {
  key: string; selectionKind: "heritage" | "feat"; name: string; acquiredLevel: number;
  featCategory: "class" | "ancestry" | "skill" | "general" | null;
  acquisitionMethod: "selected" | "awarded"; grantOrigin: string;
  validationNote?: string; sourceChronicleId?: string | null;
  characterOptionId?: string | null; sourceMaterialIdentity?: string | null;
  sourceMaterialTitle?: string | null; sourceUrl?: string | null;
};

const inputClass = "w-full rounded-xl border border-border-strong bg-surface-raised px-4 py-3 outline-none focus:border-brand";
const empty = (kind: "heritage" | "feat", level: number): CharacterOptionDraft => ({ key: crypto.randomUUID(), selectionKind: kind, name: "", acquiredLevel: level, featCategory: null, acquisitionMethod: "selected", grantOrigin: "" });

function OptionImport({ kind, onImported }: { kind: "heritage" | "feat"; onImported: (option: Awaited<ReturnType<typeof importCharacterOptionAction>> & { ok: true }) => void }) {
  const [open, setOpen] = useState(false); const [url, setUrl] = useState(""); const [message, setMessage] = useState(""); const [pending, startTransition] = useTransition();
  function submit() { startTransition(async () => { const result = await importCharacterOptionAction(url, kind); if (!result.ok) return setMessage(result.error); onImported(result); setOpen(false); setUrl(""); setMessage(""); }); }
  return <><button type="button" onClick={() => setOpen(true)} className="text-sm font-semibold text-brand hover:underline">Import from Archives of Nethys</button>{open ? <Dialog open title={`Import ${kind}`} description="Paste an official Starfinder 2e Archives of Nethys link. Manual entry remains available if import fails." onClose={() => setOpen(false)} closeLabel={`Close import ${kind}`} className="max-w-lg"><label htmlFor={`${kind}-import-url`} className="mt-5 block text-sm font-semibold">Archives of Nethys link</label><input id={`${kind}-import-url`} type="url" autoFocus value={url} onChange={(event) => { setUrl(event.currentTarget.value); setMessage(""); }} className={`mt-2 ${inputClass}`} />{message ? <p role="alert" className="mt-3 text-sm text-danger">{message}</p> : null}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setOpen(false)} className="rounded-full border border-border-strong px-4 py-2 font-semibold">Cancel</button><button type="button" onClick={submit} disabled={pending || !url.trim()} className="rounded-full bg-brand px-4 py-2 font-semibold text-on-brand disabled:opacity-60">{pending ? "Importing…" : "Import"}</button></div></Dialog> : null}</>;
}

function OptionEditor({ value, onChange, onRemove, heading }: { value: CharacterOptionDraft; onChange: (value: CharacterOptionDraft) => void; onRemove?: () => void; heading: string }) {
  const set = (patch: Partial<CharacterOptionDraft>) => onChange({ ...value, ...patch });
  return <fieldset className="rounded-xl border border-border p-4"><legend className="px-1 font-semibold">{heading}</legend><div className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><div className="flex items-center justify-between gap-3"><label htmlFor={`${value.key}-name`} className="text-sm font-semibold">Name</label><OptionImport kind={value.selectionKind} onImported={({ option }) => set({ name: option.name, characterOptionId: option.id, sourceMaterialIdentity: option.sourceMaterialIdentity, sourceMaterialTitle: option.sourceMaterialTitle, sourceUrl: option.sourceUrl, featCategory: value.selectionKind === "feat" && ["class", "ancestry", "skill", "general"].includes(String(option.metadata.featCategory)) ? option.metadata.featCategory as CharacterOptionDraft["featCategory"] : value.featCategory })} /></div><input id={`${value.key}-name`} required maxLength={200} value={value.name} onChange={(event) => set({ name: event.currentTarget.value, characterOptionId: null })} className={`mt-2 ${inputClass}`} /></div><div><label htmlFor={`${value.key}-level`} className="text-sm font-semibold">Acquired level</label><input id={`${value.key}-level`} type="number" min={1} max={20} required value={value.acquiredLevel} onChange={(event) => set({ acquiredLevel: Number(event.currentTarget.value) })} className={`mt-2 ${inputClass}`} /></div>{value.selectionKind === "feat" ? <div><label htmlFor={`${value.key}-category`} className="text-sm font-semibold">Rules category</label><StyledSelect name={`${value.key}-category`} label="Rules category" value={value.featCategory ?? ""} onValueChange={(category) => set({ featCategory: category as CharacterOptionDraft["featCategory"] || null })} options={[{ value: "", label: "Unknown" }, ...["class", "ancestry", "skill", "general"].map((category) => ({ value: category, label: `${category[0]!.toUpperCase()}${category.slice(1)} feat` }))]} /></div> : null}<fieldset><legend className="text-sm font-semibold">Acquisition</legend><div className="mt-3 flex gap-5">{(["selected", "awarded"] as const).map((method) => <label key={method} className="flex items-center gap-2 capitalize"><input type="radio" name={`${value.key}-method`} checked={value.acquisitionMethod === method} onChange={() => set({ acquisitionMethod: method })} />{method}</label>)}</div></fieldset>{value.acquisitionMethod === "awarded" ? <div><label htmlFor={`${value.key}-origin`} className="text-sm font-semibold">Grant origin <span className="font-normal text-text-muted">(optional)</span></label><input id={`${value.key}-origin`} maxLength={300} value={value.grantOrigin} onChange={(event) => set({ grantOrigin: event.currentTarget.value })} className={`mt-2 ${inputClass}`} /></div> : null}</div>{onRemove ? <button type="button" onClick={onRemove} className="mt-4 text-sm font-semibold text-danger hover:underline">Remove {value.selectionKind}</button> : null}</fieldset>;
}

export function CharacterOptionFields({ initial = [], startingLevel = 1 }: { initial?: CharacterOptionDraft[]; startingLevel?: number }) {
  const [heritage, setHeritage] = useState<CharacterOptionDraft | null>(() => initial.find(({ selectionKind }) => selectionKind === "heritage") ?? null);
  const [feats, setFeats] = useState<CharacterOptionDraft[]>(() => initial.filter(({ selectionKind }) => selectionKind === "feat"));
  const serialized = [heritage, ...feats].filter((value): value is CharacterOptionDraft => Boolean(value?.name.trim())).map((value) => ({ selectionKind: value.selectionKind, name: value.name, acquiredLevel: value.acquiredLevel, featCategory: value.featCategory, acquisitionMethod: value.acquisitionMethod, grantOrigin: value.acquisitionMethod === "awarded" ? value.grantOrigin : null, characterOptionId: value.characterOptionId, sourceMaterialIdentity: value.sourceMaterialIdentity, sourceMaterialTitle: value.sourceMaterialTitle, sourceUrl: value.sourceUrl, validationNote: value.validationNote, sourceChronicleId: value.sourceChronicleId }));
  return <fieldset className="sm:col-span-2"><legend className="text-lg font-semibold">Heritage and feats</legend><p className="mt-1 text-sm text-text-muted">Record known catalog options or type any selection manually. Unknown choices can still be saved.</p><input type="hidden" name="characterOptions" value={JSON.stringify(serialized)} /><div className="mt-4 space-y-4">{heritage ? <OptionEditor value={heritage} onChange={setHeritage} onRemove={() => setHeritage(null)} heading="Heritage" /> : <button type="button" onClick={() => setHeritage(empty("heritage", 1))} className="rounded-full border border-border-strong px-4 py-2 text-sm font-semibold">Add heritage</button>}{feats.map((feat, index) => <OptionEditor key={feat.key} value={feat} onChange={(next) => setFeats((current) => current.map((item) => item.key === feat.key ? next : item))} onRemove={() => setFeats((current) => current.filter((item) => item.key !== feat.key))} heading={`Feat ${index + 1}`} />)}<button type="button" onClick={() => setFeats((current) => [...current, empty("feat", startingLevel)])} className="rounded-full border border-border-strong px-4 py-2 text-sm font-semibold">Add feat</button></div></fieldset>;
}
