"use client";
import { useState, useTransition } from "react";
import { importCharacterOptionAction, searchCharacterOptionsAction } from "./character-options-actions";

export type SelectedCatalogOption = { id: string; name: string; sourceMaterialIdentity: string | null; sourceMaterialTitle: string | null; sourceUrl: string | null; metadata: Record<string, unknown> };
type Props = { kind: "heritage" | "feat"; category?: "class" | "ancestry" | "skill" | "general" | null; initialQuery?: string; onSelected: (option: SelectedCatalogOption) => void };
export function OptionCatalogSearch({ kind, category, initialQuery = "", onSelected }: Props) {
  const [query, setQuery] = useState(initialQuery); const [result, setResult] = useState<Awaited<ReturnType<typeof searchCharacterOptionsAction>> | null>(null);
  const [searching, startSearch] = useTransition(); const [importingUrl, setImportingUrl] = useState("");
  const search = () => startSearch(async () => setResult(await searchCharacterOptionsAction(query, kind, kind === "feat" ? category ?? undefined : undefined)));
  const chooseRemote = (url: string) => { setImportingUrl(url); startSearch(async () => { const imported = await importCharacterOptionAction(url, kind); setImportingUrl(""); if (!imported.ok) return setResult({ ok: false, error: imported.error }); onSelected(imported.option); }); };
  const hasResults = result?.ok && (result.catalog.length > 0 || result.remote.length > 0);
  return <section className="rounded-xl border border-border p-4"><h3 className="font-semibold">Find in the catalog</h3><p className="mt-1 text-sm text-text-muted">Search Nexus first, then review matching Archives of Nethys results.</p><form className="mt-3 flex flex-col gap-2 sm:flex-row" onSubmit={(event) => { event.preventDefault(); search(); }}><input type="search" aria-label={`Search ${kind}s`} value={query} minLength={2} onChange={(event) => setQuery(event.currentTarget.value)} placeholder={kind === "feat" ? "Intimidating Shot" : "Heritage name"} className="min-w-0 flex-1 rounded-xl border border-border-strong bg-surface px-3 py-2"/><button disabled={searching || query.trim().length < 2} className="rounded-full border border-border-strong px-4 py-2 text-sm font-semibold disabled:opacity-50">{searching && !importingUrl ? "Searching…" : "Search"}</button></form>
    {result && !result.ok ? <p role="alert" className="mt-3 rounded-lg bg-danger/10 p-3 text-sm text-danger">{result.error}</p> : null}
    {result?.ok && result.remoteError ? <p role="alert" className="mt-3 rounded-lg bg-warning/10 p-3 text-sm text-warning">{result.remoteError}</p> : null}
    {result?.ok && !hasResults && !result.remoteError ? <p role="status" className="mt-3 text-sm text-text-muted">No compatible {kind} results found. Try another phrase or use the link import below.</p> : null}
    {result?.ok && result.catalog.length ? <div className="mt-4"><h4 className="text-sm font-semibold">Already in Nexus</h4><ul className="mt-2 space-y-2">{result.catalog.map((option) => <li key={option.id}><button type="button" onClick={() => onSelected(option)} className="w-full rounded-lg border border-success/40 bg-success/5 p-3 text-left focus-visible:outline-3 focus-visible:outline-brand"><span className="font-semibold">{option.name}</span><span className="block text-sm text-text-muted">{option.sourceMaterialTitle ?? "Source not recorded"} · Reuse catalog entry</span></button></li>)}</ul></div> : null}
    {result?.ok && result.remote.length ? <div className="mt-4"><h4 className="text-sm font-semibold">Archives of Nethys</h4><p className="mt-1 text-xs text-text-muted">Select one result to import it. No match is chosen automatically.</p><ul className="mt-2 space-y-2">{result.remote.map((option) => <li key={option.sourceUrl}><button type="button" disabled={searching} onClick={() => chooseRemote(option.sourceUrl)} className="w-full rounded-lg border border-border-strong p-3 text-left disabled:opacity-60 focus-visible:outline-3 focus-visible:outline-brand"><span className="font-semibold">{option.name}</span><span className="block text-sm text-text-muted">{[option.sourceMaterialTitle, option.level ? `Level ${option.level}` : null, option.featCategory ? `${option.featCategory} feat` : null].filter(Boolean).join(" · ") || kind}</span>{option.summary ? <span className="mt-1 line-clamp-2 block text-sm text-text-muted">{option.summary}</span> : null}<span className="mt-1 block text-xs font-semibold text-brand">{importingUrl === option.sourceUrl ? "Importing…" : "Review and select"}</span></button></li>)}</ul></div> : null}
  </section>;
}
